/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.HospitalManagement.OperationalWorkArea;


import userInterface.SystemAdminWorkArea.*;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shreya
 */
public class OperationalPatinetEncounter extends javax.swing.JPanel {

    /**
     * Creates new form OperationalAccountsPage
     */
    JPanel userProcessContainer;
    /*EcoSystem ecosystem;
    CustomerDirectory customerDirectory;
    UserAccount userAccount;
    Customer customer;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public OperationalPatinetEncounter(JPanel userProcessContainer , EcoSystem ecosystem) {
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
//        this.ecosystem = dB4OUtil.retrieveSystem();
        if(ecosystem.getCustomerDirectory() == null)
           ecosystem.setCustomerDirectory(new CustomerDirectory());
        initComponents();
        populateTable();
    }
*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jButtonDownloadPrescription = new javax.swing.JButton();
        jButtonCreate = new javax.swing.JButton();
        jTextFieldPatientName = new javax.swing.JTextField();
        jTextFieldPatientID = new javax.swing.JTextField();
        jLabelPatientID = new javax.swing.JLabel();
        jLabelPatientName = new javax.swing.JLabel();
        jTextFieldBloodGroup = new javax.swing.JTextField();
        jTextFieldAge = new javax.swing.JTextField();
        jLabelAge = new javax.swing.JLabel();
        jLabelBloodGroup = new javax.swing.JLabel();
        jTextFieldPulse = new javax.swing.JTextField();
        jTextFieldBloodPressure = new javax.swing.JTextField();
        jLabelDiagnosisandPrescription = new javax.swing.JLabel();
        jLabelPulse = new javax.swing.JLabel();
        jTextFieldPhoneNumber = new javax.swing.JTextField();
        jTextFieldGender = new javax.swing.JTextField();
        jLabelGender = new javax.swing.JLabel();
        jLabelPhoneNumber = new javax.swing.JLabel();
        jTextFieldWeight = new javax.swing.JTextField();
        jTextFieldHeight = new javax.swing.JTextField();
        jLabelHeight = new javax.swing.JLabel();
        jLabelEmpName4 = new javax.swing.JLabel();
        jTextFieldTemparature = new javax.swing.JTextField();
        jTextFieldBMI = new javax.swing.JTextField();
        jLabelBMI = new javax.swing.JLabel();
        jLabelTemparature = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDiagnosisandPrescription = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaReasonForVisit = new javax.swing.JTextArea();
        jLabelBloodPressure = new javax.swing.JLabel();
        jLabelReasonforVisit = new javax.swing.JLabel();
        jLabelAllergies = new javax.swing.JLabel();
        jTextFieldAllergies = new javax.swing.JTextField();
        jButtonHome1 = new javax.swing.JButton();
        jButtonDownloadPrescription1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 70, 169));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Patient Encounter");
        add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 43, 706, -1));

        jButtonDownloadPrescription.setBackground(new java.awt.Color(0, 70, 169));
        jButtonDownloadPrescription.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonDownloadPrescription.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDownloadPrescription.setText("Email prescription");
        jButtonDownloadPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDownloadPrescriptionActionPerformed(evt);
            }
        });
        add(jButtonDownloadPrescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 760, -1, -1));

        jButtonCreate.setText("SUBMIT");
        add(jButtonCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 910, 100, 30));
        add(jTextFieldPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 236, 140, -1));

        jTextFieldPatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPatientIDActionPerformed(evt);
            }
        });
        add(jTextFieldPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 198, 140, -1));

        jLabelPatientID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPatientID.setText("Paatient ID:");
        add(jLabelPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 198, 104, -1));

        jLabelPatientName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPatientName.setText("Patient Name:");
        add(jLabelPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 239, 80, -1));
        add(jTextFieldBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 140, -1));

        jTextFieldAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAgeActionPerformed(evt);
            }
        });
        add(jTextFieldAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 140, -1));

        jLabelAge.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAge.setText("Age :");
        add(jLabelAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 104, -1));

        jLabelBloodGroup.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBloodGroup.setText("Blood Group :");
        add(jLabelBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, 10));
        add(jTextFieldPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 140, -1));

        jTextFieldBloodPressure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBloodPressureActionPerformed(evt);
            }
        });
        add(jTextFieldBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 140, -1));

        jLabelDiagnosisandPrescription.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDiagnosisandPrescription.setText("Diagnosis and Prescription :");
        add(jLabelDiagnosisandPrescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 630, 160, -1));

        jLabelPulse.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPulse.setText("Pulse :");
        add(jLabelPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));
        add(jTextFieldPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 140, -1));

        jTextFieldGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGenderActionPerformed(evt);
            }
        });
        add(jTextFieldGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 140, -1));

        jLabelGender.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGender.setText("Gender :");
        add(jLabelGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 104, -1));

        jLabelPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPhoneNumber.setText("Phone Number :");
        add(jLabelPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));
        add(jTextFieldWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 140, -1));

        jTextFieldHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHeightActionPerformed(evt);
            }
        });
        add(jTextFieldHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 140, -1));

        jLabelHeight.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHeight.setText("Height :");
        add(jLabelHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 104, -1));

        jLabelEmpName4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmpName4.setText("Weight :");
        add(jLabelEmpName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, -1));
        add(jTextFieldTemparature, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 140, -1));

        jTextFieldBMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBMIActionPerformed(evt);
            }
        });
        add(jTextFieldBMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 140, -1));

        jLabelBMI.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBMI.setText("B.M.I :");
        add(jLabelBMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 104, -1));

        jLabelTemparature.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTemparature.setText("Temparture :");
        add(jLabelTemparature, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, -1));

        jTextAreaDiagnosisandPrescription.setColumns(20);
        jTextAreaDiagnosisandPrescription.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDiagnosisandPrescription);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 630, 230, 120));

        jTextAreaReasonForVisit.setColumns(20);
        jTextAreaReasonForVisit.setRows(5);
        jScrollPane3.setViewportView(jTextAreaReasonForVisit);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 230, 120));

        jLabelBloodPressure.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBloodPressure.setText("Blood Pressure :");
        add(jLabelBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 104, -1));

        jLabelReasonforVisit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelReasonforVisit.setText("Reason for Visit :");
        add(jLabelReasonforVisit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 104, -1));

        jLabelAllergies.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAllergies.setText("Alllergies :");
        add(jLabelAllergies, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 780, 100, 20));
        add(jTextFieldAllergies, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 780, 230, -1));

        jButtonHome1.setBackground(new java.awt.Color(0, 70, 169));
        jButtonHome1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonHome1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHome1.setText("HOME");
        jButtonHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHome1ActionPerformed(evt);
            }
        });
        add(jButtonHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(846, 62, -1, -1));

        jButtonDownloadPrescription1.setBackground(new java.awt.Color(0, 70, 169));
        jButtonDownloadPrescription1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonDownloadPrescription1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDownloadPrescription1.setText("Download prescription");
        jButtonDownloadPrescription1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDownloadPrescription1ActionPerformed(evt);
            }
        });
        add(jButtonDownloadPrescription1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 760, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDownloadPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDownloadPrescriptionActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
            crdLyt.show(userProcessContainer,"Sysadmin");
    }//GEN-LAST:event_jButtonDownloadPrescriptionActionPerformed

    private void jTextFieldPatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPatientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPatientIDActionPerformed

    private void jTextFieldAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAgeActionPerformed

    private void jTextFieldBloodPressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBloodPressureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBloodPressureActionPerformed

    private void jTextFieldGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGenderActionPerformed

    private void jTextFieldHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHeightActionPerformed

    private void jTextFieldBMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBMIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBMIActionPerformed

    private void jButtonHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHome1ActionPerformed

    private void jButtonDownloadPrescription1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDownloadPrescription1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDownloadPrescription1ActionPerformed
    /*private Customer set_user_input_values(Customer customer, ArrayList<String> user_input){
        
        customer.getUserAccount().setPassword(user_input.get(1));
        customer.setCustomerPhone(user_input.get(2));
        return customer;
    }
        private void clearFields(){
        custUsername.setText("");
        custPassword.setText("");
        custContact.setText("");

    }
    public ArrayList<String> check_empty_field(){
        ArrayList<String> user_input = new ArrayList<>();
        String user_custName = custUsername.getText();
        String user_custPass = custPassword.getText();
        String user_contact = custContact.getText();
 
        if(user_custName.isEmpty()){
            JOptionPane.showMessageDialog(this, "Customer Name can't be left empty");
        }
        else if(user_custPass.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter password");
        }
        
        else if(user_contact.isEmpty()){
            JOptionPane.showMessageDialog(this, "Customer Contact No can't be left empty.");
        }
        user_input.add(user_custName);
        user_input.add(user_custPass);
        user_input.add(user_contact);
        
        return user_input;
        
    }
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonDownloadPrescription;
    private javax.swing.JButton jButtonDownloadPrescription1;
    private javax.swing.JButton jButtonHome1;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelAllergies;
    private javax.swing.JLabel jLabelBMI;
    private javax.swing.JLabel jLabelBloodGroup;
    private javax.swing.JLabel jLabelBloodPressure;
    private javax.swing.JLabel jLabelDiagnosisandPrescription;
    private javax.swing.JLabel jLabelEmpName4;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelHeight;
    private javax.swing.JLabel jLabelPatientID;
    private javax.swing.JLabel jLabelPatientName;
    private javax.swing.JLabel jLabelPhoneNumber;
    private javax.swing.JLabel jLabelPulse;
    private javax.swing.JLabel jLabelReasonforVisit;
    private javax.swing.JLabel jLabelTemparature;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaDiagnosisandPrescription;
    private javax.swing.JTextArea jTextAreaReasonForVisit;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldAllergies;
    private javax.swing.JTextField jTextFieldBMI;
    private javax.swing.JTextField jTextFieldBloodGroup;
    private javax.swing.JTextField jTextFieldBloodPressure;
    private javax.swing.JTextField jTextFieldGender;
    private javax.swing.JTextField jTextFieldHeight;
    private javax.swing.JTextField jTextFieldPatientID;
    private javax.swing.JTextField jTextFieldPatientName;
    private javax.swing.JTextField jTextFieldPhoneNumber;
    private javax.swing.JTextField jTextFieldPulse;
    private javax.swing.JTextField jTextFieldTemparature;
    private javax.swing.JTextField jTextFieldWeight;
    // End of variables declaration//GEN-END:variables
/*
    private void populateTable() {
        
        customerDirectory = ecosystem.getCustomerDirectory();
        ArrayList<Customer> customers = customerDirectory.getCustomerList();
        DefaultTableModel model = (DefaultTableModel) customersTable.getModel();
        model.setRowCount(0);
//        DefaultComboBoxModel dc = new DefaultComboBoxModel();
        
        for(Customer c: customers)
        {
            model.addRow(new Object[]{c,c.getUserAccount().getPassword(), c.getCustomerPhone()});
//            dc.addElement(c.getCustomerName());
        }
        customersTable.setModel(model);
//        listCustomers.setModel(dc);
        dB4OUtil.storeSystem(ecosystem);
    }*/
}
