/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.HospitalManagement.MedTechnicalWorkArea;

import HospitalManagement.Hospital.Hospital;
import userInterface.SystemAdminWorkArea.*;
import MainCentralisationSystem.MedicalServiceCentralisationEcoSystem;
import MainCentralisationSystem.HospitalManagementEnterprise;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
//import userinterface.createNewUser.createLogin;

public class MedTechnicalWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    MedicalServiceCentralisationEcoSystem medicalServiceCentralisationEcoSystem;
    Hospital hospital;
    public MedTechnicalWorkAreaJPanel(JPanel userProcessContainer,MedicalServiceCentralisationEcoSystem medicalServiceCentralisationEcoSystem, Hospital hospital) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.medicalServiceCentralisationEcoSystem = medicalServiceCentralisationEcoSystem;
        this.hospital = hospital;
        jPanel1.setVisible(false);
        //jSplitPane.setVisible(false);
        //jPanel2.setVisible(true);
//        populateTree();
    }
    
    public void populateTree(){
        //DefaultTreeModel model=(DefaultTreeModel)Admin.getModel();
       // Add the code for draw your system structure shown by JTree
       
      //  model.reload();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonTestDatabase = new javax.swing.JButton();
        jButtonEmployeeAttendance = new javax.swing.JButton();
        jButtonPatientTest = new javax.swing.JButton();
        bgdimg = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1720, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSplitPane.setPreferredSize(new java.awt.Dimension(1720, 1080));

        jPanel1.setPreferredSize(new java.awt.Dimension(0, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jSplitPane.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1920, 1183));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonTestDatabase.setBackground(new java.awt.Color(0, 0, 0));
        jButtonTestDatabase.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonTestDatabase.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTestDatabase.setText("Test Database");
        jButtonTestDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestDatabaseActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonTestDatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 360, 590, 50));

        jButtonEmployeeAttendance.setBackground(new java.awt.Color(0, 0, 0));
        jButtonEmployeeAttendance.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonEmployeeAttendance.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEmployeeAttendance.setText("Employee Attendance");
        jButtonEmployeeAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmployeeAttendanceActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEmployeeAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 450, 590, 50));

        jButtonPatientTest.setBackground(new java.awt.Color(0, 0, 0));
        jButtonPatientTest.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonPatientTest.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPatientTest.setText("Patient Test");
        jButtonPatientTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPatientTestActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPatientTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 540, 590, 50));

        bgdimg.setBackground(new java.awt.Color(255, 255, 255));
        bgdimg.setForeground(new java.awt.Color(255, 255, 255));
        bgdimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Images/MedTechnicalWorkAreaJPanel.png"))); // NOI18N
        jPanel2.add(bgdimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1920, 1190));

        jSplitPane.setRightComponent(jPanel2);

        add(jSplitPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1833, 1102));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEmployeeAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmployeeAttendanceActionPerformed
//        MedTechnicalEmployeeAttendance medTechnicalEmployeeAttendance = new MedTechnicalEmployeeAttendance(userProcessContainer,medicalServiceCentralisationEcoSystem);
//        userProcessContainer.add("medTechnicalEmployeeAttendance",medTechnicalEmployeeAttendance);
//        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
//        cardLayout.show(userProcessContainer,"medTechnicalEmployeeAttendance");
    }//GEN-LAST:event_jButtonEmployeeAttendanceActionPerformed

    private void jButtonTestDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestDatabaseActionPerformed

        MedTechnicalTestDatabase medTechnicalTestDatabase = new MedTechnicalTestDatabase(userProcessContainer,medicalServiceCentralisationEcoSystem, hospital);
        userProcessContainer.add("medTechnicalTestDatabase",medTechnicalTestDatabase);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.show(userProcessContainer,"medTechnicalTestDatabase");
    }//GEN-LAST:event_jButtonTestDatabaseActionPerformed

    private void jButtonPatientTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPatientTestActionPerformed
        // TODO add your handling code here:
        MedTechnicalPatientTest medTechnicalPatientTest = new MedTechnicalPatientTest(userProcessContainer,medicalServiceCentralisationEcoSystem, hospital);
        userProcessContainer.add("medTechnicalPatientTest",medTechnicalPatientTest);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.show(userProcessContainer,"medTechnicalPatientTest");
    }//GEN-LAST:event_jButtonPatientTestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgdimg;
    private javax.swing.JButton jButtonEmployeeAttendance;
    private javax.swing.JButton jButtonPatientTest;
    private javax.swing.JButton jButtonTestDatabase;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane;
    // End of variables declaration//GEN-END:variables
}
